name: CI

on:
  workflow_dispatch:

jobs:
  build-and-test-hgl:
    name: Build & Test HungryGhostReverb (macOS)
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Show Xcode info
        run: |
          xcodebuild -version
          xcode-select -p

      - name: Configure HungryGhostReverb (Xcode generator)
        run: |
          cmake -S src/HungryGhostReverb -B src/HungryGhostReverb/build -G Xcode

      - name: Build tests (Debug)
        run: |
          cmake --build src/HungryGhostReverb/build --config Debug --target HGLTests_DSP HGLTests_Proc

      - name: Run tests (DSP)
        run: |
          ./src/HungryGhostReverb/build/HGLTests_DSP_artefacts/Debug/HGLTests_DSP

      - name: Run tests (Processor)
        run: |
          ./src/HungryGhostReverb/build/HGLTests_Proc_artefacts/Debug/HGLTests_Proc

      - name: Build plugin (Release)
        run: |
          cmake --build src/HungryGhostReverb/build --config Release --target HungryGhostReverb_VST3

      - name: Upload plugin artefacts (VST3 Bundle)
        uses: actions/upload-artifact@v4
        with:
          name: HungryGhostReverb-vst3-macos
          path: |
            src/HungryGhostReverb/build/HungryGhostReverb_artefacts/Release/VST3/**/*.vst3
            src/HungryGhostReverb/build/HungryGhostReverb_artefacts/Release/VST3/**/*.vst3/**


